# Generated by Django 4.2 on 2025-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_usuario', models.CharField(max_length=50, unique=True, verbose_name='Código de Usuario')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área/Departamento')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario'), ('MANAGER', 'Gerente'), ('SUPERVISOR', 'Supervisor')], default='USER', max_length=20, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
            ],
            options={
                'verbose_name': 'Usuario SAP HANA',
                'verbose_name_plural': 'Usuarios SAP HANA',
                'db_table': 'GARMENT_PRODUCTION_CONTROL.T_USUARIOS',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
