# Generated by Django 4.2 on 2025-06-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_color', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion_color', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_creativo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_foto', models.CharField(blank=True, max_length=30, null=True)),
                ('ruta_foto', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linea', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sublinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sublinea', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnico', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tela', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_tela', models.CharField(blank=True, max_length=200, null=True)),
                ('ancho', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_color', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_color', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_variacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaSublinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_app.linea')),
                ('sublinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_app.sublinea')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo_sap_md', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo_sap_pt', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_sistema', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_color', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_color', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_referente', models.CharField(blank=True, max_length=20, null=True)),
                ('tallaje', models.CharField(blank=True, max_length=50, null=True)),
                ('largo', models.CharField(blank=True, max_length=50, null=True)),
                ('modista', models.CharField(blank=True, max_length=100, null=True)),
                ('creativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_creativo', to='costeo_app.creativo')),
                ('foto_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colecciones_foto_referencia', to='costeo_app.foto')),
                ('foto_tela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_foto_tela', to='costeo_app.foto')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_linea', to='costeo_app.linea')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_status', to='costeo_app.status')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_tecnico', to='costeo_app.tecnico')),
            ],
        ),
    ]
