# Generated by Django 4.2 on 2024-10-14 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creativos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCreativo', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoFoto', models.CharField(blank=True, max_length=30, null=True)),
                ('rutaFoto', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linea', models.CharField(blank=True, max_length=20, null=True)),
                ('sublinea', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTecnico', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_tela', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_tela', models.CharField(blank=True, max_length=30, null=True)),
                ('ancho', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_color', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_color', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoSapMD', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoSapPT', models.CharField(blank=True, max_length=30, null=True)),
                ('nombreSistema', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcionColor', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoColor', models.CharField(blank=True, max_length=20, null=True)),
                ('nombreReferente', models.CharField(blank=True, max_length=20, null=True)),
                ('tallaje', models.CharField(blank=True, max_length=50, null=True)),
                ('largo', models.CharField(blank=True, max_length=50, null=True)),
                ('modista', models.CharField(blank=True, max_length=100, null=True)),
                ('creativo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_creativo', to='costeo_app.creativos')),
                ('fotoReferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecciones_foto_referencia', to='costeo_app.fotos')),
                ('fotoTela', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_foto_tela', to='costeo_app.fotos')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_linea', to='costeo_app.lineas')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_status', to='costeo_app.status')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_tecnico', to='costeo_app.tecnicos')),
            ],
        ),
    ]
