# Generated by Django 4.2 on 2024-10-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color_Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoColor', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcionColor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCreativo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoFoto', models.CharField(blank=True, max_length=30, null=True)),
                ('rutaFoto', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linea', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sublinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sublinea', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTecnico', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tela', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_tela', models.CharField(blank=True, max_length=200, null=True)),
                ('ancho', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_color', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_color', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_variacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoSapMD', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoSapPT', models.CharField(blank=True, max_length=30, null=True)),
                ('nombreSistema', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcionColor', models.CharField(blank=True, max_length=200, null=True)),
                ('codigoColor', models.CharField(blank=True, max_length=20, null=True)),
                ('nombreReferente', models.CharField(blank=True, max_length=20, null=True)),
                ('tallaje', models.CharField(blank=True, max_length=50, null=True)),
                ('largo', models.CharField(blank=True, max_length=50, null=True)),
                ('modista', models.CharField(blank=True, max_length=100, null=True)),
                ('creativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_creativo', to='costeo_app.creativo')),
                ('fotoReferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colecciones_foto_referencia', to='costeo_app.foto')),
                ('fotoTela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_foto_tela', to='costeo_app.foto')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_linea', to='costeo_app.linea')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_status', to='costeo_app.status')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_tecnico', to='costeo_app.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='LineaSublinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_app.linea')),
                ('sublinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costeo_app.sublinea')),
            ],
            options={
                'unique_together': {('linea', 'sublinea')},
            },
        ),
    ]
