# Generated by Django 4.2 on 2024-10-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color_referencia',
            name='codigoColor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='color_referencia',
            name='descripcionColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
