# Generated by Django 4.2 on 2025-07-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('codigo_referencia', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
