# Generated by Django 4.2 on 2025-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0002_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAnchoUtil',
            fields=[
                ('ancho_util_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ancho_util_metros', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_ANCHO_UTIL"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimBaseTextil',
            fields=[
                ('base_textil_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base_textil_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_BASE_TEXTIL"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCantidadTelas',
            fields=[
                ('cantidad_telas_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_telas_numero', models.IntegerField()),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_CANTIDAD_TELAS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCaracteristicaColor',
            fields=[
                ('caracteristica_color_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('caracteristica_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_CARACTERISTICA_COLOR"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimDescripcion',
            fields=[
                ('descripcion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('detalle_descripcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_DESCRIPCION"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPrenda',
            fields=[
                ('prenda_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_prenda_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_PRENDA"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPropiedadesTela',
            fields=[
                ('propiedades_tela_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('al_hilo_flag', models.BooleanField(default=False)),
                ('al_sesgo_flag', models.BooleanField(default=False)),
                ('noventa_grados_flag', models.BooleanField(default=False)),
                ('peine_flag', models.BooleanField(default=False)),
                ('brilloviz_flag', models.BooleanField(default=False)),
                ('grabado_flag', models.BooleanField(default=False)),
                ('sentido_moldes_flag', models.CharField(max_length=50)),
                ('canal_tela_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_PROPIEDADES_TELA"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTerminacion',
            fields=[
                ('terminacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria_terminacion', models.CharField(max_length=50)),
                ('tipo_terminacion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_TERMINACION"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimUsoTela',
            fields=[
                ('uso_tela_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uso_tela_nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_USO_TELA"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimVariante',
            fields=[
                ('variante_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_variante', models.IntegerField()),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."DIM_VARIANTE"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactConsumo',
            fields=[
                ('consumo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consumo_mtr', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': '"CONSUMO_TEXTIL"."FACT_CONSUMO"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Referencia',
        ),
    ]
