# Generated by Django 5.2.1 on 2025-06-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0002_alter_color_referencia_codigocolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
