# Generated by Django 4.2 on 2024-10-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0002_alter_status_status_alter_telas_descripcion_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='descripcionColor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creativos',
            name='nombreCreativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='rutaFoto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineas',
            name='linea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lineas',
            name='sublinea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tecnicos',
            name='nombreTecnico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
