# Generated by Django 5.2.1 on 2025-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_color', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion_color', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Color_Referencia',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='codigoColor',
            new_name='codigo_color',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='codigoSapMD',
            new_name='codigo_sap_md',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='codigoSapPT',
            new_name='codigo_sap_pt',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='descripcionColor',
            new_name='descripcion_color',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='fotoReferencia',
            new_name='foto_referencia',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='fotoTela',
            new_name='foto_tela',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='nombreReferente',
            new_name='nombre_referente',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='nombreSistema',
            new_name='nombre_sistema',
        ),
        migrations.RenameField(
            model_name='creativo',
            old_name='nombreCreativo',
            new_name='nombre_creativo',
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='rutaFoto',
            new_name='ruta_foto',
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='tipoFoto',
            new_name='tipo_foto',
        ),
        migrations.RenameField(
            model_name='tecnico',
            old_name='nombreTecnico',
            new_name='nombre_tecnico',
        ),
    ]
