# Generated by Django 4.2 on 2024-10-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0004_rename_tecnicos_creativo_rename_fotos_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_creativo', to='costeo_app.creativo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_tecnico', to='costeo_app.tecnico'),
        ),
    ]
