# Generated by Django 4.2 on 2025-06-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0004_colorreferencia_delete_color_referencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
