# Generated by Django 4.2 on 2024-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0005_alter_collection_creativo_alter_collection_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('es_variacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
