# Generated by Django 4.2 on 2024-10-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0006_variacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_creativo', to='costeo_app.creativo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='fotoReferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colecciones_foto_referencia', to='costeo_app.foto'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='fotoTela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_foto_tela', to='costeo_app.foto'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_linea', to='costeo_app.linea'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_status', to='costeo_app.status'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colecciones_tecnico', to='costeo_app.tecnico'),
        ),
    ]
