# Generated by Django 4.2 on 2024-10-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0007_alter_collection_creativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorReferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoColor', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcionColor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
