# Generated by Django 4.2 on 2024-10-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costeo_app', '0008_colorreferencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorReferencia',
            new_name='Color_Referencia',
        ),
    ]
