# Generated by Django 4.2.30 on 2026-05-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SapImageAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("image", models.ImageField(upload_to="sap/images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SapParametroRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("base_textil", models.CharField(max_length=120)),
                ("tela", models.CharField(max_length=120)),
                ("ancho", models.DecimalField(decimal_places=2, max_digits=5)),
                ("print_name", models.CharField(max_length=120)),
                ("hilo_de_tela", models.CharField(max_length=120)),
                ("hilo_de_molde", models.CharField(max_length=120)),
                ("canal_tela", models.CharField(max_length=120)),
                ("sentido_sesgos", models.CharField(max_length=120)),
                ("rotacion_molde", models.CharField(max_length=120)),
                ("restricciones_tela", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
